export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_LOADING = 'SET_LOADING'
export const SET_CONTROLLERS = 'SET_CONTROLLERS'
export const SET_STINFOS = 'SET_STINFOS'
